# -*- coding: utf-8 -*-
"""Task1: Credit score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fe9LhLiATLCoFcT8GuOFrZe-toEUdkyQ
"""

import pandas as pd
import numpy as np

df  =pd.read_csv('credit_score_dataset.csv')
df.head()

X = df.iloc[:, 1:-1]
X

y = df.iloc[:, -1]
y

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

#  Train a Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=42)
model.fit(X_train_scaled, y_train)

# Make Predictions and Evaluate
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, roc_curve

y_pred = model.predict(X_test_scaled)
y_proba = model.predict_proba(X_test_scaled)[:, 1]

conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred, output_dict=True)
roc_auc = roc_auc_score(y_test, y_proba)

(conf_matrix, class_report, roc_auc)

